# Generated by Django 5.2.13 on 2026-05-10 18:32

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
        ('assets_management_plugin', '0002_assetgroup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetgroup',
            options={'ordering': ('-last_updated',)},
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('device_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_period_months', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('warranty_expiration_date', models.DateField(blank=True, editable=False, null=True)),
                ('asset_group', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets_management_plugin.assetgroup')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.location')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ('-last_updated',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
